name: paper-supp-binder
channels:
  - conda-forge
dependencies:
  - python=3.11.10
  - pip=24.2
  - numpy=1.26.4
  - scipy=1.13.1
  - pandas=2.2.2
  - matplotlib=3.9.2
  - seaborn=0.13.2
  - scikit-image=0.24.0
  - pyvista=0.44.1
  - vtk=9.3.1
  - tqdm=4.66.5
  - numba=0.60.0
  - paramiko=3.5.0
  - ipykernel=6.29.5
  - jupyterlab=4.2.5
  - notebook=7.2.2
  - pip:
      - imageio==2.35.1
      - meshio==5.3.5
      - numpy-stl==3.1.2
      - opencv-python==4.10.0.84
      - scp==0.15.0
