name: paper-supp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=1.26
  - pandas=2.2
  - matplotlib=3.9
  - scipy=1.13
  - pip
  - pip:
      - imageio
      - pyvista
      - opencv-python
      - meshio
